version: '3.7'
services:
  apache:
    build: apache
    ports:
      - '8040:80'
    volumes:
      - openmct-dist:/usr/local/apache2/htdocs/openmct
    networks:
      - docker_openmct_link
    extra_hosts:
      - "host.docker.internal:host-gateway"
  openmct:
    build: openmct
    volumes:
      - openmct-dist:/openmct/site
    networks:
      - docker_openmct_link
    extra_hosts:
      - "host.docker.internal:host-gateway"
  couchdb:
    build: couchdb
    expose:
      - '5984:5984'
    networks:
      - docker_openmct_link
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - couchdb-data:/opt/couchdb/data
  yamcs:
    build: yamcs
    expose:
      - '8090:8090'
      - '10015:10015/udp'
    networks:
      - docker_openmct_link
    extra_hosts:
      - "host.docker.internal:host-gateway"
  simulator:
    build: simulator
    networks:
      - docker_openmct_link
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
    - yamcs
volumes:
  couchdb-data:
  openmct-dist:
networks:
  docker_openmct_link:
    name: docker_openmct_link
    driver: bridge